New deployments with different environments. LI-37

diff --git a/.github/workflows/job.depoy.yml b/.github/workflows/job.depoy.yml
--- a/.github/workflows/job.depoy.yml
+++ b/.github/workflows/job.depoy.yml
@@ -4,9 +4,10 @@ name: Deploy
 on:
   workflow_call:
     inputs:
-      environment: { required: true, type: string }
-      config_file: { required: true, type: string }
-      branch:      { required: true, type: string }
+      environment: { required: true,  type: string }
+      config_file: { required: true,  type: string }
+      branch:      { required: true,  type: string }
+      service:     { required: false, type: string, default: lord }
     secrets:
       GAME_HOST:   { required: true }
       GAME_PORT:   { required: true }
@@ -29,13 +30,24 @@ jobs:
           user: ${{ secrets.DEPLOY_USER }}
           key:  ${{ secrets.DEPLOY_KEY }}
           command: |
-            set -e
-            cd /srv/luanti/accounts/lord/games/lord/
-            sudo -u ${{ secrets.GAME_USER }} git checkout ${{ inputs.branch }}
-            sudo -u ${{ secrets.GAME_USER }} git pull --recurse-submodules
-            sudo -u ${{ secrets.GAME_USER }} git submodule init
-            sudo -u ${{ secrets.GAME_USER }} git submodule update
-            sudo -u ${{ secrets.GAME_USER }} cp -f ${{ inputs.config_file }} minetest.conf
-            sudo -u ${{ secrets.GAME_USER }} sudo systemctl restart lord
+            sudo -u ${{ secrets.GAME_USER }} bash -s << 'EOF'
+              set -e
+              cd /srv/luanti/accounts/lord/${{ inputs.environment }}/game/lord/
+              git checkout ${{ inputs.branch }}
+              git pull --recurse-submodules
+              git submodule init
+              git submodule update
+              cp -f ${{ inputs.config_file }} minetest.conf
+              echo 'Restarting lord service...'
+              sudo systemctl restart ${{ inputs.service }}
+              sleep 3
+              if systemctl is-active --quiet ${{ inputs.service }}; then
+                echo 'Service successfully restarted'
+                exit 0
+              else
+                echo 'Service failed to start' >&2
+                exit 1
+              fi
+            EOF
           args: -tt
-    
+
