test deploy 5

diff --git a/.github/workflows/job.depoy.yml b/.github/workflows/job.depoy.yml
--- a/.github/workflows/job.depoy.yml
+++ b/.github/workflows/job.depoy.yml
@@ -44,7 +44,14 @@ jobs:
               cp -f ${{ inputs.config_file }} minetest.conf
               echo "Restarting lord service..."
               sudo systemctl restart lord
-              echo "Service restarted successfully"
+              echo "After service restarted"
+              sleep 3
+              if systemctl is-active --quiet lord; then
+                echo "Service is running successfully"
+              else
+                echo "Service failed to start" >&2
+                exit 1
+              fi
             '
           args: -tt
     
